version: '3.3'
services:
    master_db:
        container_name: "mysql_master"
        image: actency/docker-mysql-replication:5.7
        ports:
          - "3307:3306"
        restart: always
        volumes: 
          - ./data/mysql-master:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: mysqlroot
          MYSQL_USER: example_user
          MYSQL_PASSWORD: mysqlpwd
          MYSQL_DATABASE: example
          REPLICATION_USER: replication_user
          REPLICATION_PASSWORD: myreplpassword

    slave_db:
        container_name: "mysql_slave"
        image: actency/docker-mysql-replication:5.7
        ports:
            - "3308:3306"
        restart: always
        volumes: 
          - ./data/mysql-slave:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: mysqlroot
          MYSQL_USER: example_user
          MYSQL_PASSWORD: mysqlpwd
          MYSQL_DATABASE: example
          REPLICATION_USER: replication_user
          REPLICATION_PASSWORD: myreplpassword
        depends_on:
          - master_db
        links:
          - "master_db:master"

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080